name: Python checks

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
    - uses: actions/setup-python@v4
    - run: pip install pylint  # -r requirements.txt
    - run: pylint *.py
